START_TIME: '2023-04-02T17:00:00Z'
TIMEOUT: 300_000 

CONFIDENCE_LEVELS:
  strong: 0.8
  consolidated: 0.5
  weak: 0.1

hotspots:
  THRESHOLDS:
    hot: 0.06
    burn: 0.03

formats:
  DATE:
    hour12: true
    hour: 2-digit
    minute: 2-digit
